/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Todo": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Todo.id"];
          created_at?: parameters["rowFilter.Todo.created_at"];
          owner?: parameters["rowFilter.Todo.owner"];
          todo?: parameters["rowFilter.Todo.todo"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Todo"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Todo */
          Todo?: definitions["Todo"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Todo.id"];
          created_at?: parameters["rowFilter.Todo.created_at"];
          owner?: parameters["rowFilter.Todo.owner"];
          todo?: parameters["rowFilter.Todo.todo"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Todo.id"];
          created_at?: parameters["rowFilter.Todo.created_at"];
          owner?: parameters["rowFilter.Todo.owner"];
          todo?: parameters["rowFilter.Todo.todo"];
        };
        body: {
          /** Todo */
          Todo?: definitions["Todo"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Todo: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: uuid */
    owner: string;
    /** Format: ARRAY */
    todo?: string[];
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Todo */
  "body.Todo": definitions["Todo"];
  /** Format: bigint */
  "rowFilter.Todo.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Todo.created_at": string;
  /** Format: uuid */
  "rowFilter.Todo.owner": string;
  /** Format: ARRAY */
  "rowFilter.Todo.todo": string;
}

export interface operations {}

export interface external {}
